
TAGS_INFO2 = {
            "abstract": {"keep": True, "cor": "ABSTRACT", "examples": ['season', 'extra_+_time', 'goal', 'goals', 'seconds']},
            "agent_of_action": {"keep": True, "cor": "AGENT_OF_ACTION", "examples": ['sends', 'play', 'beaten', 'said', 'means']},
            "agent_of_verb": {"keep": True, "cor": "AGENT_OF_VERB", "examples": ['Sheffield_+_United', 'victory', 'they', 'Harry', 'it']},
            "antecedent": {"keep": True, "cor": "ANTECEDENT", "examples": ['who', 'They', 'It', 'that', 'it']},
            "antecedent_of_relpro": {"keep": True, "cor": "ANTECEDENT_OF_RELPRO", "examples": ['final', 'players', 'fans', 'himself', 'Martin']},
            "apposition_to": {"keep": True, "cor": "APPOSITION_TO", "examples": ['3-2', 'Kane', "Eriksen's", '3-2', '1']},
            "closing_quote_ptr": {"keep": False, "cor": "CLOSING_QUOTE_PTR", "examples": ["'", 'means', 'the', 'world', "'"]},
            "comparative": {"keep": True, "cor": "COMPARATIVE", "examples": ['better', 'younger', 'earlier', 'better', 'young']},
            "dirobj": {"keep": True, "cor": "DIROBJ", "examples": ['on', 'in', 'sends', 'to', 'play']},
            "dirobj_of": {"keep": True, "cor": "DIROBJ_OF", "examples": ['aggregate', 'CupThe', 'side', 'WembleyThey', 'Chelsea']},
            "emphatic": {"keep": True, "cor": "EMPHATIC", "examples": ['make', 'leave', 'seem', 'offer', 'have']},
            "event": {"keep": True, "cor": "EVENT", "examples": ['victory', 'win', 'cruise', 'warm-up', 'clash']},
            "future": {"keep": True, "cor": "FUTURE", "examples": ['play', 'meet', 'facing', 'back', 'give']},
            "govern": {"keep": True, "cor": "GOVERN", "examples": ['on', 'in', 'sends', 'to', 'play']},
            "governed_by": {"keep": True, "cor": "GOVERNED_BY", "examples": ['on', 'in', 'to', 'in', 'for']},
            "governs_another_noun": {"keep": True, "cor": "GOVERNS_ANOTHER_NOUN", "examples": ['beat', 'Sheffield_+_United', 'side', 'double', 'Sheffield_+_United']},
            "governs_nonfinite": {"keep": False, "cor": "GOVERNS_NONFINITE", "examples": ['could', 'United', 'can', 'had_+_to', 'could']},
            "has_apposition": {"keep": True, "cor": "HAS_APPOSITION", "examples": ['Sheffield_+_United', 'Harry', 'Cup.Christian', 'win', 'Sky_+_Sports']},
            "human": {"keep": True, "cor": "HUMAN", "examples": ["Mauricio_+_Pochettino's", 'side', 'Chelsea', 'they', 'Harry']},
            "indirobj": {"keep": True, "cor": "INDIROBJ", "examples": ['beaten', 'giving', 'scored', 'missed', 'made']},
            "indirobj_of": {"keep": True, "cor": "INDIROBJ_OF", "examples": ['who', 'Londoners', 'character', 'it', 'it']},
            "infinitive": {"keep": True, "cor": "INFINITIVE", "examples": ['reach', 'send', 'put', 'happen', 'play']},
            "linked_to_predicate": {"keep": True, "cor": "LINKED_TO_PREDICATE", "examples": ['was', "'s", "'s", "there's", 'was']},
            "location": {"keep": True, "cor": "LOCATION", "examples": ['Tottenham', 'final', 'Tottenham', 'final', 'goal']},
            "modified_by_adj": {"keep": True, "cor": "MODIFIED_BY_ADJ", "examples": ['CupThe', 'victory', "Eriksen's", 'Spurs', 'goal']},
            "modified_by_adverb": {"keep": True, "cor": "MODIFIED_BY_ADVERB", "examples": ['avoided', 'Wembley', 'on', 'looked', "'s"]},
            "modified_by_prep1": {"keep": True, "cor": "MODIFIED_BY_PREP1", "examples": ['Sheffield_+_United', 'aggregate', 'sends', 'Chelsea', 'world']},
            "modified_by_prep2": {"keep": True, "cor": "MODIFIED_BY_PREP2", "examples": ['talks', 'booked', 'catapulted', 'drafted', '’re']},
            "modified_on_left": {"keep": True, "cor": "MODIFIED_ON_LEFT", "examples": ['CupThe', 'victory', 'final', 'season', 'world']},
            "modified_on_right": {"keep": True, "cor": "MODIFIED_ON_RIGHT", "examples": ['Tottenham', 'Spurs', 'goal', 'Kane', 'Flynn']},
            "modifies": {"keep": True, "cor": "MODIFIES", "examples": ['extra_+_time', 'on_+_March_+_1', 'ahead', 'likely', 'season']},
            "modifies_another_noun": {"keep": True, "cor": "MODIFIES_ANOTHER_NOUN", "examples": ['Tottenham', 'beat', "Mauricio_+_Pochettino's", 'Cup.Christian', 'League_+_One']},
            "modifies_left_head": {"keep": True, "cor": "MODIFIES_LEFT_HEAD", "examples": ['reach', 'avoided', 'giving', 'left', 'right']},
            "modifies_right_head": {"keep": True, "cor": "MODIFIES_RIGHT_HEAD", "examples": ['the', 'Capital', 'One', 'semi-final', 'the']},
            "neg": {"keep": True, "cor": "NEG", "examples": ['could', 'is', 'trust', 'had', 'back']},
            "next_enum": {"keep": True, "cor": "NEXT_ENUM", "examples": ['we', 'had', 'missed', 'fans', 'score']},
            "nfw": {"keep": True, "cor": "NFW", "examples": ['3-2', 'CupThe', 'WembleyThey', 'Kane', 'Cup.Christian']},
            "nonfinite_governed_by": {"keep": True, "cor": "NONFINITE_GOVERNED_BY", "examples": ['done', 'put', 'happen', 'play', 'fault']},
            "object_of_action": {"keep": True, "cor": "OBJECT_OF_ACTION", "examples": ['sends', 'play', 'beaten', 'reach', 'ensured']},
            "object_of_verb": {"keep": True, "cor": "OBJECT_OF_VERB", "examples": ['side', 'Chelsea', 'season', 'final', 'Spurs']},
            "opening_quote_ptr": {"keep": True, "cor": "OPENING_QUOTE_PTR", "examples": ["'", 'means', 'the', 'world', "'"]},
            "passive": {"keep": True, "cor": "PASSIVE", "examples": ['fouled', 'booked', 'sent', 'drafted', 'picked']},
            "past": {"keep": True, "cor": "PAST", "examples": ['said', 'ensured', 'told', 'were', 'was']},
            "perfect": {"keep": True, "cor": "PERFECT", "examples": ['beaten', 'made', 'had', 'fouled', 'booked']},
            "physub": {"keep": True, "cor": "PHYSUB", "examples": ['aggregate', 'world', 'aggregate', 'world', 'possession']},
            "pl": {"keep": True, "cor": "PL", "examples": ['Spurs', 'Londoners', 'scores', 'goals', 'seconds']},
            "predadj_of": {"keep": True, "cor": "PREDADJ_OF", "examples": ['thing', '1-1', 'decider', 'place', 'proud']},
            "present": {"keep": True, "cor": "PRESENT", "examples": ['sends', 'beaten', 'means', 'means', 'battles']},
            "previous_enum": {"keep": True, "cor": "PREVIOUS_ENUM", "examples": ['crowd', 'got', 'for', 'players', 'kill']},
            "progressive": {"keep": True, "cor": "PROGRESSIVE", "examples": ['facing', 'refereeing', 'looking_+_for', 'dreaming', 'listening']},
            "refl": {"keep": True, "cor": "REFL", "examples": ['get', 'established']},
            "semantic_modifier_of": {"keep": True, "cor": "SEMANTIC_MODIFIER_OF", "examples": ['Capital', 'semi-final', 'Capital', 'avoided', 'late']},
            "sg": {"keep": True, "cor": "SG", "examples": ['Tottenham', 'beat', 'aggregate', 'CupThe', 'victory']},
            "skip_begin": {"keep": True, "cor": "SKIP_BEGIN", "examples": ['will', 'battles', 'scored', ',', ',']},
            "skip_end": {"keep": True, "cor": "SKIP_END", "examples": ['CupThe', 'Kane', 'character', 'Wembley', 'manager']},
            "superlative": {"keep": True, "cor": "SUPERLATIVE", "examples": ['worst', 'STRONGEST', 'biggest', 'best', 'best']},
            "time": {"keep": True, "cor": "TIME", "examples": ['season', 'extra_+_time', 'seconds', 'night', 'Extra-time']}
            }

# [["abstract", "Tottenham"], ["agent_of_action", "send"], 
# ["agent_of_verb", "Sheffield_+_United"], ["antecedent", "who"], ["antecedent_of_relpro", "final"],
#  ["apposition_to", "3-2"], ["closing_quote_ptr", "'"], ["comparative", "better"], ["det", "Tottenham"], 
#  ["dirobj", "on"], ["dirobj_of", "aggregate"], ["emphatic", "make"], ["event", "Tottenham"], 
#  ["future", "play"], ["govern", "on"], ["governed_by", "on"], ["governs_another_noun", "beat"], 
#  ["governs_nonfinite", "could"], ["has_apposition", "Sheffield_+_United"], ["human", "Tottenham"], 
#  ["indirobj", "beat"], ["indirobj_of", "who"], ["infinitive", "reach"], ["linked_to_predicate", "be"], 
#  ["location", "Tottenham"], ["modified_by_adj", "CupThe"], ["modified_by_adverb", "avoid"], 
#  ["modified_by_prep1", "Sheffield_+_United"], ["modified_by_prep2", "talk"], ["modified_on_left", "CupThe"], 
#  ["modified_on_right", "Tottenham"], ["modifies", "extra_+_time"], ["modifies_another_noun", "Tottenham"], 
#  ["modifies_left_head", "reach"], ["modifies_right_head", "the"], ["nb", "send"], ["neg", "could"], 
#  ["next_enum", "we"], ["nfw", "3-2"], ["nonfinite_governed_by", "do"], ["object_of_action", "send"],
#   ["object_of_verb", "side"], ["oldtag", "Tottenham"], ["opening_quote_ptr", "'"], ["passive", "foul"], 
#   ["past", "say"], ["per", "send"], ["perfect", "beat"], ["physub", "Tottenham"], ["pl", "spur"], 
#   ["predadj_of", "thing"], ["present", "send"], ["previous_enum", "crowd"], ["progressive", "face"], 
#   ["refl", "get"], ["semantic_modifier_of", "capital"], ["sg", "Tottenham"], 
# ["skip_begin", "will"], ["skip_end", "CupThe"], ["superlative", "bad"], ["time", "Tottenham"]]


CORRESPONDANCE = {"modified_by_prep1": "MODIFIED_BY_PREP1", 
                  "sg": "SG", "nb": "NB", "predadj_of": "PREDADJ_OF", 
                  "governs_nonfinite": "GOVERNS_NONFINITE", "dirobj_of": "DIROBJ_OF", 
                  "modified_by_adj": "MODIFIED_BY_ADJ", "opening_quote_ptr": "OPENING_QUOTE_PTR", 
                  "emphatic": "EMPHATIC", "object_of_action": "OBJECT_OF_ACTION", 
                  "antecedent": "ANTECEDENT", "semantic_modifier_of": "SEMANTIC_MODIFIER_OF", 
                  "dirobj": "DIROBJ", "governs_another_noun": "GOVERNS_ANOTHER_NOUN", 
                  "antecedent_of_relpro": "ANTECEDENT_OF_RELPRO", "modified_on_right": "MODIFIED_ON_RIGHT", 
                  "future": "FUTURE", "govern": "GOVERN", "modifies_another_noun": "MODIFIES_ANOTHER_NOUN", 
                  "indirobj": "INDIROBJ", "modified_by_prep2": "MODIFIED_BY_PREP2", 
                  "apposition_to": "APPOSITION_TO", "neg": "NEG", "has_apposition": "HAS_APPOSITION", 
                  "nfw": "NFW", "perfect": "PERFECT", "pl": "PL", "present": "PRESENT", 
                  "oldtag": "OLDTAG", "abstract": "ABSTRACT", "passive": "PASSIVE", 
                  "location": "LOCATION", "next_enum": "NEXT_ENUM", "modifies_right_head": "MODIFIES_RIGHT_HEAD", 
                  "closing_quote_ptr": "CLOSING_QUOTE_PTR", "time": "TIME", "event": "EVENT", 
                  "governed_by": "GOVERNED_BY", "modifies_left_head": "MODIFIES_LEFT_HEAD", 
                  "infinitive": "INFINITIVE", "agent_of_verb": "AGENT_OF_VERB", "human": "HUMAN", 
                  "nonfinite_governed_by": "NONFINITE_GOVERNED_BY", "per": "PER", "refl": "REFL", 
                  "superlative": "SUPERLATIVE", "past": "PAST", "previous_enum": "PREVIOUS_ENUM", 
                  "modified_by_adverb": "MODIFIED_BY_ADVERB", "modified_on_left": "MODIFIED_ON_LEFT", 
                  "linked_to_predicate": "LINKED_TO_PREDICATE", "modifies": "MODIFIES", "skip_end": "SKIP_END", 
                  "skip_begin": "SKIP_BEGIN", "comparative": "COMPARATIVE", "object_of_verb": "OBJECT_OF_VERB", 
                  "det": "DET", "indirobj_of": "INDIROBJ_OF", "agent_of_action": "AGENT_OF_ACTION", 
                  "physub": "PHYSUB", "progressive": "PROGRESSIVE"}

ALL_TAGS = ["det", "human", "location", "physub",
            "event", "abstract", "time", "sg",
            "oldtag", "modifies_another_noun",
            "governs_another_noun", "agent_of_verb",
            "has_apposition", "modified_by_prep1", "nfw",
            "apposition_to", "dirobj", "govern", "governed_by",
            "dirobj_of", "modifies_right_head", "semantic_modifier_of",
            "modified_by_adj", "modified_on_left", "skip_end", "nb", "per",
            "present", "agent_of_action", "object_of_action", "object_of_verb",
            "skip_begin", "future", "antecedent_of_relpro", "antecedent",
            "indirobj_of", "perfect", "indirobj", "past", "closing_quote_ptr",
            "opening_quote_ptr", "modified_on_right", "infinitive",
            "modifies_left_head", "pl", "modified_by_adverb", "modifies",
            "linked_to_predicate", "superlative", "predadj_of", "governs_nonfinite",
            "nonfinite_governed_by", "progressive", "comparative", "previous_enum",
            "next_enum", "neg", "modified_by_prep2",
            "passive", "emphatic", "refl"]


# tous les tags qui donnent des relations (lient à un autre mot)
RELATIONS = ["agent_of_action", "agent_of_verb", "antecedent",
             "antecedent_of_relpro", "apposition_to", "closing_quote_ptr",
             "dirobj", "dirobj_of", "govern", "governed_by", "governs_another_noun",
             "governs_nonfinite", "has_apposition", "indirobj", "indirobj_of",
             "linked_to_predicate", "modified_by_adj", "modified_by_adverb",
             "modified_by_prep1", "modified_by_prep2", "modified_on_left",
             "modified_on_right", "modifies", "modifies_another_noun", "modifies_left_head",
             "modifies_right_head", "next_enum", "nonfinite_governed_by", "object_of_action",
             "object_of_verb", "opening_quote_ptr", "predadj_of", "previous_enum",
             "semantic_modifier_of", "skip_begin", "skip_end"]


# tous les tags qui valent soit 0 soit 1
OTHER = ["abstract", "comparative", "emphatic", "event", "future",
         "human", "infinitive", "location", "neg", "nfw", "passive",
         "past", "perfect", "physub", "pl", "present", "progressive",
         "refl", "sg", "superlative", "time"]


# tous les tags qu'on trouve sur des verbes
VERB_TAGS = ["agent_of_action", "agent_of_verb", "apposition_to", 
             "closing_quote_ptr", "dirobj", "dirobj_of", "emphatic", 
             "future", "govern", "governed_by", "governs_another_noun", 
             "governs_nonfinite", "has_apposition", "human", "indirobj", 
             "indirobj_of", "infinitive", "linked_to_predicate", 
             "modified_by_adj", "modified_by_adverb", "modified_by_prep1", 
             "modified_by_prep2", "modified_on_left", "modified_on_right", 
             "modifies", "modifies_another_noun", "modifies_left_head", 
             "modifies_right_head", "nb", "neg", "next_enum", "nfw", 
             "nonfinite_governed_by", "object_of_action", "object_of_verb", 
             "oldtag", "opening_quote_ptr", "passive", "past", "per", "perfect", 
             "predadj_of", "present", "previous_enum", "progressive", "refl", 
             "semantic_modifier_of", "skip_begin", "skip_end"]
# examples [["agent_of_action", "send"], ["agent_of_verb", "mean"], 
# ["apposition_to", "celebrate"], ["closing_quote_ptr", "mean"], 
# ["dirobj", "send"], ["dirobj_of", "unite"], ["emphatic", "make"], 
# ["future", "play"], ["govern", "send"], ["governed_by", "miss"], 
# ["governs_another_noun", "sign"], ["governs_nonfinite", "unite"], 
# ["has_apposition", "sing"], ["human", "let_x_us"], ["indirobj", "beat"], 
# ["indirobj_of", "pick"], ["infinitive", "reach"], ["linked_to_predicate", "feel"], 
# ["modified_by_adj", "beat"], ["modified_by_adverb", "avoid"], 
# ["modified_by_prep1", "send"], ["modified_by_prep2", "talk"], 
# ["modified_on_left", "score"], ["modified_on_right", "beat"], 
# ["modifies", "do_x_not"], ["modifies_another_noun", "roar"], 
# ["modifies_left_head", "reach"], ["modifies_right_head", "unite"], 
# ["nb", "send"], ["neg", "trust"], ["next_enum", "miss"], 
# ["nfw", "gamesLosing"], ["nonfinite_governed_by", "do"], 
# ["object_of_action", "send"], ["object_of_verb", "score"], 
# ["oldtag", "send"], ["opening_quote_ptr", "mean"], ["passive", "foul"], 
# ["past", "say"], ["per", "send"], ["perfect", "beat"], 
# ["predadj_of", "referee"], ["present", "send"], ["previous_enum", "get"], 
# ["progressive", "face"], ["refl", "get"], ["semantic_modifier_of", "avoid"], 
# ["skip_begin", "battle"], ["skip_end", "demand"]]


NOUN_TAGS = ["abstract", "agent_of_verb", "antecedent_of_relpro", 
             "apposition_to", "closing_quote_ptr", "det", "dirobj", 
             "dirobj_of", "event", "govern", "governs_another_noun", 
             "governs_nonfinite", "has_apposition", "human", "indirobj_of", 
             "location", "modified_by_adj", "modified_by_adverb", 
             "modified_by_prep1", "modified_by_prep2", "modified_on_left", 
             "modified_on_right", "modifies",
             "modifies_another_noun", "next_enum",
             "nfw", "object_of_action", "object_of_verb", "oldtag",
             "opening_quote_ptr", "physub", "pl", "predadj_of",
             "previous_enum", "sg", "skip_begin", "skip_end", "time"]
# examples [["abstract", "Tottenham"], ["agent_of_verb", "Sheffield_+_United"],
# ["antecedent_of_relpro", "final"], ["apposition_to", "Kane"],
# ["closing_quote_ptr", "world"], ["det", "Tottenham"], ["dirobj", "controversy"],
# ["dirobj_of", "aggregate"], ["event", "Tottenham"], ["govern", "controversy"],
# ["governs_another_noun", "beat"], ["governs_nonfinite", "need"],
# ["has_apposition", "Sheffield_+_United"], ["human", "Tottenham"],
# ["indirobj_of", "londoner"], ["location", "Tottenham"], ["modified_by_adj", "CupThe"],
# ["modified_by_adverb", "Wembley"], ["modified_by_prep1", "Sheffield_+_United"],
# ["modified_by_prep2", "fee"], ["modified_on_left", "CupThe"],
# ["modified_on_right", "Tottenham"], ["modifies", "extra_+_time"],
# ["modifies_another_noun", "Tottenham"], ["next_enum", "fan"],
# ["nfw", "CupThe"], ["object_of_action", "controversy"], ["object_of_verb", "side"],
# ["oldtag", "Tottenham"], ["opening_quote_ptr", "world"], ["physub", "Tottenham"],
# ["pl", "spur"], ["predadj_of", "thing"], ["previous_enum", "crowd"], ["sg", "Tottenham"],
# ["skip_begin", "stand"], ["skip_end", "CupThe"], ["time", "Tottenham"]]

